blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('post_list/', views.post_list, name="post_list"),
    path('post/new/', views.post_new, name="post_new"),
    path('post/draft/', views.post_draft_list, name="post_draft_list"),
    
    path('post/<int:pk>/', views.post_detail, name="post_detail"),
    path('post/<int:pk>/publish/', views.post_publish, name="post_publish"),
    path('post/<int:pk>/edit/', views.post_edit, name="post_edit"),
    path('post/<int:pk>/delete/', views.post_delete, name="post_delete"),
    path('post/<int:pk>/comment', views.add_comment_to_post, name="add_comment_to_post"),
    
    path('comment/<int:pk>/approve', views.comment_approve, name="comment_approve"),
    path('comment/<int:pk>/remove', views.comment_remove, name="comment_remove"),
]

travelsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:index'), name='root'), # URL Reverse
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

travelsite/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11; IE=10; IE=8; IE7; IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" href='{% static "css/blog.css" %}'>
    <link rel="shortcut icon" href="#">
    <style type="text/css">
      /* a:link { color:#868686; text-decoration: none;} */
      a:visited { color:#868686; text-decoration: none;}
      a:hover { color:#008299; text-decoration: underline;;}
    </style>
</head>
<body>
  <div class="container">
    <div class="row">
        {% block body %}{% endblock %}
        
      </div>
    </div>
    <hr />
    &copy; 2019. daseulll



    
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

travelsite/templates/layout.html
<!doctype html>
{% load static fresh_static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Travel{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="{% static "css/lib/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/lib/bootstrap-grid.min.css" %}">
    <link rel="stylesheet" href="{% static "css/lib/bootstrap-reboot.min.css" %}"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href='{% fresh_static "css/base.css" %}'>
    <link rel="stylesheet" href='{% fresh_static "css/blog.css" %}'>
    {% block extra_head %}{% endblock %}
</head>
<body>
  <div class="container">
    <div class="row">
      {% block body %}{% endblock %}
      <hr />
      &copy; 2019. daseulll
    </div>
  </div>

  <script src="{% static "js/lib/bootstrap.min.js" %}"></script>
  <script src="{% static "js/lib/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

travelsite/templates/navbar.html
<div class="container">
  {% if user.is_anonymous %}
    <header class="blog-header nav-1 py-3">
  {% else %}
    <header class="blog-header py-3">
  {% endif %}
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted" href="/"><i class="fas fa-plane fa-3x"></i></a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="/">Travel</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3" focusable="false" role="img"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
        </a>
        {% if user.is_authenticated %}
        <span>안녕하세요, {{ user.username }}님</span>
        <span>
          <small>(<a href="{% url 'signout' %}">Logout</a>)</small>
        </span>
        {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'signin' %}?next={{ reqeust.path }}">로그인</a>
        {% endif %}
      </div>
    </div>
  </header>
  {% if user.is_authenticated %}
  <div class="py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="#">World</a>
      <a class="p-2 text-muted" href="#">U.S.</a>
      <a class="p-2 text-muted" href="#">Europe</a>
      <a class="p-2 text-muted" href="#">Asia</a>
      <a class="p-2 text-muted" href="#"></a>
      <a class="p-2 text-muted" href="#"></a>
      <a class="p-2 text-muted" href="#"></a>
      <a class="p-2 text-muted" href="#"></a>
      <a class="p-2 text-muted" href="{% url "profile" %}">내 정보</a>
      <a class="p-2 text-muted" href="{% url 'blog:post_list' %}">내 글보기</a>
      <a class="p-2 text-muted text-dark " href="{% url 'blog:post_new' %}">
        <i class="fas fa-plus"></i>
      </a>
    </nav>
  </div>
  {% endif %}
</div>

travelsite/templates/navbar_detail.html
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted" href="/"><i class="fas fa-plane fa-3x"></i></a>
      </div>
      <div class="col-4 text-center">
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3" focusable="false" role="img"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
        </a>
        {% if user.is_authenticated %}
        <span>안녕하세요, {{ user.username }}님</span>
        <span>
          <small>(<a href="{% url 'signout' %}">Logout</a>)</small>
        </span>
        {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'signin' %}">로그인</a>
        {% endif %}
      </div>
    </div>
  </header>
</div>