accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('profile/', views.profile, name="profile"),
    path('profile/edit/', views.profile_edit, name="profile_edit"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('post_list/', views.post_list, name="post_list"),
    path('post/new/', views.post_new, name="post_new"),
    path('post/draft/', views.post_draft_list, name="post_draft_list"),
    
    path('post/<int:pk>/', views.post_detail, name="post_detail"),
    path('post/<int:pk>/publish/', views.post_publish, name="post_publish"),
    path('post/<int:pk>/edit/', views.post_edit, name="post_edit"),
    path('post/<int:pk>/delete/', views.post_delete, name="post_delete"),
    path('post/<int:pk>/comment', views.add_comment_to_post, name="add_comment_to_post"),
    
    path('comment/<int:pk>/approve', views.comment_approve, name="comment_approve"),
    path('comment/<int:pk>/remove', views.comment_remove, name="comment_remove"),
]

travelsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:index'), name='root'), # URL Reverse
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(
        upload_to='blog/image',
        blank=True,
        verbose_name='대표이미지',
        )
    image_thumbnail = ProcessedImageField(
        upload_to='blog/thumbnail',
        processors=[ResizeToFill(100, 50)],
        format='JPEG',
        options={'quality' : 80},
        blank=True,
    )
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True,
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)
        
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.CharField(max_length=200)
    text = models.CharField(max_length=300)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return "{}에 작성됨 - {} : {} ".format(self.post.title, self.author, self.text)

blog/forms.py
from django import forms
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import Post, Comment

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)   
        self.fields['title'].widget.attrs.update({'class':'form-control'})
        text= self.fields['text'].widget = SummernoteWidget()
   
    class Meta:
        model = Post
        fields = ('title', 'text', 'image', )
        image_thumbnail = ProcessedImageField(
            spec_id='blog:post:image_thumbnail',
            processors=[ResizeToFill(100, 50)],
            format='JPEG',
            options={'quality' : 80},
            verbose_name="대표이미지",
        )

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)   
        self.fields['author'].widget.attrs.update({'class':'form-control-sm'})
        self.fields['text'].widget.attrs.update({'class':'form-control'})
   
    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm


def index(request):
    if request.method == "GET":
        posts = Post.objects.filter(published_date__isnull=False)
    return render(request, "blog/index.html", {"posts" : posts})


@login_required
def post_list(request):
    if request.method == "GET":
        posts = Post.objects.filter(author=request.user)

    return render(request, "blog/post_list.html", {'posts':posts})

@login_required
def post_detail(request, pk):
    # post = get_object_or_404(Post, pk=pk)
    if request.method == "GET":
        post = Post.objects.get(pk=pk)
    return render(request, "blog/post_detail.html", {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_list')
    else:
        form = PostForm()

    return render(request, "blog/post_edit.html", {'form' : form})

@login_required
def post_edit(request, pk):
    if request.method == "POST":
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:post_detail', pk )
    else:
        post = Post.objects.get(pk=pk)
        if post.author == request.user:
            post = Post.objects.get(pk=pk)
            form = PostForm(instance=post)
            return render(request, "blog/post_edit.html", {'form' : form})
        else:
            return render(request, 'accounts/warning.html')
            


@login_required
def post_draft_list(request):
    draft_posts = Post.objects.filter(published_date__isnull=True, author=request.user).order_by('created_date')
    return render(request, "blog/post_draft_list.html", {
        "draft_posts": draft_posts,
    })

@login_required
def post_publish(request, pk):
    post = Post.objects.get(pk=pk)
    if post.author == request.user:
        post.publish()
    else:
        return render(request, 'accounts/warning.html')
    
    return redirect('blog:post_detail', pk)

@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if post.author == request.user:
        post.delete()
    else:
        return render(request, 'accounts/warning.html')
    return redirect('blog:post_list')

def add_comment_to_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk)
    else:
        form = CommentForm()

    return render(request, "blog/add_comment_to_post.html", {"form":form})

@login_required
def comment_approve(request, pk):
    comment = Comment.objects.get(pk=pk)
    comment.approve()
    return redirect('blog:post_list')

@login_required
def comment_remove(request, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()
    return redirect('blog:post_list', pk)

blog/templates/blog/add_comment_to_post.html
{% extends "blog/layout.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="col-sm-12">
  <h1>New comment</h1>
    <form method="POST" class="post-form">
      {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-outline-primary">Send</button>
    </form>
  </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/layout.html" %}
{% block title %}index{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="row">
  <div class="col-7">
    <img style="width:100%; height:90%"src="/static/sea.jpg" alt="">
  </div>
    <div class="col-5">
      <div class="text-info rounded bg-white">
        <h1 class="display-4">Memorize trip</h1>
          <p class="lead my-3">
            여행을 기록하세요.<br>
            더 많은 것을 느끼고 추억하게 되실거에요.<br>
          </p>
      </div>
    </div>
  </div>
  <hr />
  <div class="row">
    {% for post in posts  %}
    <div class="col-sm-3">
      <div class="card border-light mb-3" style="width: 15rem;">
        {% if post.image %}
          <img src="{{ post.image.url }}" class="card-img-top" style="width: 250px; height:200px;"/>
        {% endif %}
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'blog:post_detail' post.pk %}">
                {{ post.title }}
              </a>
            </h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% block body %}
{% include "navbar_detail.html" %}

<div class="col-10 content text-center">
  <div class="content-header"><h2>{{ post.title }}</h2></div>
  {% if post.image %}   
    <img src="{{ post.image.url }}" class="post_image" width="200px" />
  {% endif %}
    <p>{{ post.text|safe }}</p>
  
    {% if post.published_date %}
      <p class="date">{{ post.published_date }}</p>
    {% else %}
      {% if post.author == user %}
        <a class="btn btn-outline-success" href="{% url 'blog:post_publish' post.pk %}">발행</a>
      {% endif %}
    {% endif %}
  
    {% if post.author == user %}
      <a class="btn btn-default content text-center" href="{% url 'blog:post_edit' post.pk %}">
        <i class="fas fa-pencil-alt"></i>
      </a>
      <a class="btn btn-default" href="{% url 'blog:post_delete' post.pk %}">
       <i class="far fa-trash-alt"></i>
     </a>
    {% endif %}
</div>

<div class="comment">
  {% for comment in post.comments.all %}
  {% if user.is_authenticated or comment.approved_comment %}
  <div>
      {{ comment.author }} : {{ comment.text }}
      <div class="date">{{ comment.created_date }}
        {% if not comment.approved_comment %}
          <a class="btn btn-default" href="{% url 'blog:comment_approve' comment.pk %}">
            <span class="glyphicon glyphicon-remove">
              댓글승인
            </span>
          </a>
        {% endif %}
        <a class="btn btn-default" href="{% url 'blog:comment_remove' comment.pk %}">
            삭제
        </a>
      </div>
    </div>
  {% endif %}
{% empty %}
<hr />
<p><small>댓글이 아직 없습니다.</small></p>
{% endfor %}
<a href="{% url 'blog:add_comment_to_post' post.pk %}">Add Comment</a>
<hr />
<a href="{% url 'blog:post_list' %}">글목록</a>

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "blog/layout.html" %}
{% block body %}
{% include "navbar.html" %}
    
<div class="post">
    <h1>임시저장글</h1>

    {% for post in draft_posts %}
        <h2><a href="{% url 'blog:post_detail' post.pk %}">
            {{ post.title }}<small> (댓글:{{ post.approved_comments.count }})</small>
        </a></h2>
    {% endfor %}        
    <a href="{% url 'blog:post_list' %}">전체목록</a>
</div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/layout.html' %}
{% block body %}
{% include "navbar.html" %}
<div class="col-sm-6 offset-sm-3">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <h1>New post</h1>
        {{ form.as_p }}
      <button type="submit" class="save btn btn-outline-secondary">Save</button>
    </div>
  </form>
  {% endblock %}
</div>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}
{% block title %}내 글보기{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="col-sm-12">
  <div class="post">
    <h1 class="blog-header">나의 게시글</h1>
    {% for post in posts %}
      {% if post.published_date %}

      <div class="row">
        <div class="col-sm-3 list">
        {% if post.image_thumbnail %}
          <img src="{{ post.image_thumbnail.url }}" class="post_image" />
        {% endif %}
        </div>
          <div class="col-sm-9 list">
            <h3><a href="{% url 'blog:post_detail' post.pk %}">
              {{ post.title }}<small> (댓글:{{ post.approved_comments.count }})</small>
            </a></h3>
          <p class="date">{{ post.published_date }}</p>
          </div>
        </div>
        {% endif %}    
    {% endfor %}

      <a href="{% url 'blog:post_draft_list' %}" class="top-menu">
        <span class="glyphicon glyphicon-edit">임시저장목록</span>
      </a>
    </div>
  </div>
{% endblock %}

blog/templates/blog/signin.html
{% extends "base.html" %}
{% block title %}index{% endblock %}
{% block body %}
{% include "navbar.html" %}
<form method="post" action="" class="form-signin">
  {% csrf_token %}
  <h1 class="h3 mb-3 my-2 font-weight-normal">로그인</h1>
  <label for="inputName" class="sr-only">Username</label>
  <input type="username" name="username" class="form-control" placeholder="Username" required="" autofocus="">
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" name="password" class="form-control" placeholder="Password" required="">
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
    <div style="font-size:13px">{{ fail }}</div>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">로그인</button>
  <p style="margin-top:1rem;"><a href="{% url 'blog:signup' %}">회원가입</a></p>
</form>
{% endblock %}